name: Build and Deploy
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.IMAGE_REGISTRY_TOKEN }}

      # Assumes the Deploy action below leaves existing videos there :)
      - name: "Check if animations changed"
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            manim:
              - "manim_animations/**"
      - name: Build Videos ğŸ¥
        if: steps.filter.outputs.manim == 'true'
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/animlbook/animl-devcontainer
          push: never
          runCmd: make manim
      - name: Build Book (HTML) ğŸ“–
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/animlbook/animl-devcontainer
          push: never
          runCmd: make html
      - name: Deploy ğŸš€
        if: github.event_name == 'push'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: book_source/source/_build/html

